### ISSUE TITLE
Add quote search functionality

### ISSUE THREAD

**Issue by joswin18** [joswin18/MotivateMe-chrome-Extension#3]
### Add quote search functionality

**Comment by mohsenkhosroanjam** [comment]
@joswin18 Hi, I hope you are doing well. Would you like to assign it to me? I would love to try implementing it.

**Comment by joswin18** [comment]
@mohsenkhosroanjam, I'll assign it to you. Let me know if you have any questions.

**Comment by joswin18** [comment]
thank you for participating, This issue has been resolved. In the meantime, feel free to check out other open issues
